In [1]:
from sklearn.datasets import make_blobs
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [5]:
X = pd.read_csv(r"C:\Users\joelm\Documents\handson-ml3\Joel\adult.data", header=None)

In [6]:
X.shape

(32561, 15)

In [9]:
X.columns = ["age","workclass","fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","salary"]

In [11]:
X.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  salary  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [14]:
X2 = pd.get_dummies(X, columns=['workclass', 'education', 'marital-status'])
X2.head()

age  fnlwgt  education-num          occupation    relationship    race  \
0   39   77516             13        Adm-clerical   Not-in-family   White   
1   50   83311             13     Exec-managerial         Husband   White   
2   38  215646              9   Handlers-cleaners   Not-in-family   White   
3   53  234721              7   Handlers-cleaners         Husband   Black   
4   28  338409             13      Prof-specialty            Wife   Black   

       sex  capital-gain  capital-loss  hours-per-week  ...  \
0     Male          2174             0              40  ...   
1     Male             0             0              13  ...   
2     Male             0             0              40  ...   
3     Male             0             0              40  ...   
4   Female             0             0              40  ...   

  education_ Preschool education_ Prof-school  education_ Some-college  \
0                    0                      0                        0   
1                    0                      0                        0   
2                    0                      0                        0   
3                    0                      0                        0   
4                    0                      0                        0   

   marital-status_ Divorced  marital-status_ Married-AF-spouse  \
0                         0                                  0   
1                         0                                  0   
2                         1                                  0   
3                         0                                  0   
4                         0                                  0   

   marital-status_ Married-civ-spouse  marital-status_ Married-spouse-absent  \
0                                   0                                      0   
1                                   1                                      0   
2                                   0                                      0   
3                                   1                                      0   
4                                   1                                      0   

   marital-status_ Never-married  marital-status_ Separated  \
0                              1                          0   
1                              0                          0   
2                              0                          0   
3                              0                          0   
4                              0                          0   

   marital-status_ Widowed  
0                        0  
1                        0  
2                        0  
3                        0  
4                        0  

[5 rows x 44 columns]

In [15]:
X3 = pd.get_dummies(X)
X3.head()

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   

   workclass_ ?  workclass_ Federal-gov  workclass_ Local-gov  \
0             0                       0                     0   
1             0                       0                     0   
2             0                       0                     0   
3             0                       0                     0   
4             0                       0                     0   

   workclass_ Never-worked  ...  native-country_ Scotland  \
0                        0  ...                         0   
1                        0  ...                         0   
2                        0  ...                         0   
3                        0  ...                         0   
4                        0  ...                         0   

   native-country_ South  native-country_ Taiwan  native-country_ Thailand  \
0                      0                       0                         0   
1                      0                       0                         0   
2                      0                       0                         0   
3                      0                       0                         0   
4                      0                       0                         0   

   native-country_ Trinadad&Tobago  native-country_ United-States  \
0                                0                              1   
1                                0                              1   
2                                0                              1   
3                                0                              1   
4                                0                              0   

   native-country_ Vietnam  native-country_ Yugoslavia  salary_ <=50K  \
0                        0                           0              1   
1                        0                           0              1   
2                        0                           0              1   
3                        0                           0              1   
4                        0                           0              1   

   salary_ >50K  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 110 columns]

In [35]:
y = X3.iloc[:,109]
y

0        0
1        0
2        0
3        0
4        0
        ..
32556    0
32557    1
32558    0
32559    0
32560    1
Name: salary_ >50K, Length: 32561, dtype: uint8

In [37]:
from sklearn.preprocessing import StandardScaler

In [39]:
Z = 100*np.random.rand(200, 4)+50
Z

array([[ 60.46016199,  50.76259112,  57.45638735, 131.4196526 ],
       [120.10831575, 140.34645857,  98.71062523, 130.5936547 ],
       [112.9355034 , 111.49762901, 118.80757874, 124.37702989],
       [ 90.38344221, 127.32318336, 127.89271394, 107.15142203],
       [ 82.40914575,  52.5494904 ,  71.66976289,  83.2445123 ],
       [118.52479495,  55.52225536,  58.54658271, 107.72467195],
       [121.65258805,  97.11477225,  71.47015117,  63.60521529],
       [ 82.29102868, 110.80877437, 145.30382885,  67.98923907],
       [118.93128753, 106.89672172, 146.07823988,  66.93374134],
       [118.94735675, 135.13540978,  56.49546482,  74.41151274],
       [ 79.51196276,  57.46695493, 140.09874751,  61.81076356],
       [ 96.02196865, 149.01065853, 101.59839397,  74.53662427],
       [ 90.97018553, 110.16017017,  76.92347055,  61.68603987],
       [140.86979361, 104.39217827,  56.13269532, 112.43740378],
       [121.53193355,  97.84221807, 110.85067949,  95.85816358],
       [116.64631961, 143

In [40]:
Z.mean(axis=0)

array([102.22010491,  99.191903  , 100.7808019 , 100.70489399])

In [41]:
Z.std(axis = 0)

array([28.96872766, 28.50933403, 29.46106643, 27.85898477])

In [42]:
s = StandardScaler()
Z_scaled = s.fit_transform(Z)
print(Z_scaled.mean(axis = 0))
print(Z_scaled.std(axis = 0))

[-2.91600077e-15 -2.20296004e-15 -2.72941392e-16  6.06181771e-16]
[1. 1. 1. 1.]
